### ISSUE TITLE
The snow flakes freeze in between falling

### ISSUE THREAD

**Issue by ChinmayMR** [TheIcyStar/IcyStorm#3]
Is this a problem of my low end pc or what.

Thanks in advance

https://user-images.githubusercontent.com/69135158/134797564-1fa3ec16-ae13-453e-86fd-6585080f723d.mp4

**Comment by TheIcyStar** [comment]
I believe it is from tour low specs, but it is quite odd that it freezes intermittently and then comes back to full speed.

What are your specs, (cpu, ram, etc) and what is the ram usage of rainmeter like? Does it spike downward after the freeze?

**Comment by ChinmayMR** [comment]
I have a Core i5, 8GB Ram, no gpu and I think I found the problem it is when I enable other skins like the cpu ram skins it lags. If I turn them of then the snow is smooth with no problems. So is there any way to stop this error?

**Comment by TheIcyStar** [comment]
Try out a different cpu & ram meter skin combo to see if the issue still persists

also anything in the console? (Right click rainmeter icon in dock > manage > open log)

**Comment by ChinmayMR** [comment]
I tried out a different ram and skin meter(https://www.deviantart.com/rasylver/art/Lines-2-0-154719861) and no lag. So I guess it is problem of https://www.deviantart.com/flyinghyrax/art/CircuitousTwo-376652231. The log 
![image](https://user-images.githubusercontent.com/69135158/135014026-66d5a2a4-185b-4b22-99eb-ceffa733c8f8.png)

This is the only thing I found in the log and is it related to an error rest are just refreshing notices.

**Comment by TheIcyStar** [comment]
Glad you were able to find a solution. Logs look relatively clean.

**Comment by ChinmayMR** [comment]
Um did the system skin use too much CPU or why did this happen I am curious

**Comment by ChinmayMR** [comment]
@TheIcyStar

**Comment by TheIcyStar** [comment]
Not sure, I would have to open their skin to get an idea of what is going on. Please contact the creator of that skin to let them know of the issue.

**Comment by ChinmayMR** [comment]
Arn't you the creator of the skin?

**Comment by ChinmayMR** [comment]
@TheIcyStar

**Comment by TheIcyStar** [comment]
The creator of your cpu/ram display skin

**Comment by ChinmayMR** [comment]
Oh ok

**Comment by ChinmayMR** [comment]
Nah I prob gonna keep quiet
