### ISSUE TITLE
Request to optimize lcyStorm's LUA script

### ISSUE THREAD

**Issue by Purehowaito** [TheIcyStar/IcyStorm#4]
Hello RhelcyStar author, I've been using your LUA script for 1 year and love it, but it doesn't feel particularly smooth, there will be noticeable stuttering when moving, especially when I record it at 60 frames,I also know that it is caused by integrity and constant animation, high update rate, massive size, but I would like to give it a try, if you feel that you can and are interested, can you optimize your LUA script?

**Comment by TheIcyStar** [comment]
I've wanted to do this for a long while, but never got around to doing it... but anyways, it's done!
I've rewritten the script to use vastly less calls to rainmeter with each update frame. Hopefully the performance will be better for you.

You can find version 2.1.0 under the [releases tab](https://github.com/TheIcyStar/IcyStorm/releases/) of this repository.
